### ISSUE TITLE
ImportError of numpy.

### ISSUE THREAD

**Issue by hansyuanyang** [tito91/memreport-tool#1]
Hi tito91, this seems a cool tool. But I got ImportError of NumPy. Which NumPyversion are you originally using? I'm using UE4.27(Python version 3.7) and NumPy 1.21.4.  Thank you

**Comment by tito91** [comment]
Hello @hansyuanyang! I was using Python 3.7 and NumPy 1.18.4 for this project.

**Comment by tito91** [comment]
Strange, I've just updated all of the required packages (NumPy 1.21.4, Matplotlib 3.5.0, Anytree 2.8.0) and project still runs. Have you tried to run this project in clean virtual environment? Maybe something's wrong with the current environment.

**Comment by hansyuanyang** [comment]
Yes, I did install my NumPy in virtual env. I will do more tests and let you know the result. Thanks.

**Comment by hansyuanyang** [comment]
Hi, I downloaded again today and install couple of module it needs. And everything works fine! Really cool tool. Thank you.
